CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;
CREATE TABLE IF NOT EXISTS users (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  login VARCHAR(20) NOT NULL,
  password VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS products (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  price INTEGER,
  PRIMARY KEY (ID)
);

INSERT INTO users (login, password)
SELECT * FROM (SELECT 'admin', '{SHA}QL0AFWMIX8NRZTKeof9cXsvbvu8=') AS tmp
WHERE NOT EXISTS (
    SELECT login FROM users WHERE login='admin' AND password='123'
) LIMIT 1;

INSERT INTO products (name, price)
SELECT * FROM (SELECT 'FENDER SQUIER', 30000) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM products WHERE name = 'FENDER SQUIER' AND price = 30000
) LIMIT 1;

INSERT INTO products (name, price)
SELECT * FROM (SELECT 'Artesia DP-7', 40480) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM products WHERE name = 'Artesia DP-7' AND price = 40480
) LIMIT 1;

INSERT INTO products (name, price)
SELECT * FROM (SELECT 'TUTTI JR-11', 1427) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM products WHERE name = 'TUTTI JR-11' AND price = 1427
) LIMIT 1;

INSERT INTO products (name, price)
SELECT * FROM (SELECT 'IBANEZ GRX70QA', 28900) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM products WHERE name = 'IBANEZ GRX70QA' AND price = 28900
) LIMIT 1;

INSERT INTO products (name, price)
SELECT * FROM (SELECT 'IBANEZ GRG', 35000) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM products WHERE name = 'IBANEZ GRG' AND price = 35000
) LIMIT 1;


